summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-linux-loongarch64/releases/download/2025.01.09/pkg-config-0.29.2-linux-loongarch64.release.tar.xz
bin-sha: 5d137c611277e912db8e9347d90ad8f53052dcc4a5f56650192d0a0653d86603
